DROP DATABASE IF EXISTS alphaVoterDB;
CREATE DATABASE alphaVoterDB;

DROP DATABASE IF EXISTS voterHistoryDB;
CREATE DATABASE voterHistoryDB;

DROP DATABASE IF EXISTS usersDB;
CREATE DATABASE usersDB;

DROP DATABASE IF EXISTS voterInteractionsDB;
CREATE DATABASE voterInteractionsDB;